/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuzzRouteImport } from './routes/buzz'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShowcaseIndexRouteImport } from './routes/showcase/index'
import { Route as ShowcaseSlugRouteImport } from './routes/showcase/$slug'
import { Route as ShowcaseAdminRouteImport } from './routes/showcase/admin'
import { Route as ShowcaseMineRouteImport } from './routes/showcase/mine'
import { Route as ShowcaseSubmitRouteImport } from './routes/showcase/submit'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ShowcaseBuilderHandleRouteImport } from './routes/showcase/builder.$handle'
import { Route as ShowcaseEditItemIdRouteImport } from './routes/showcase/edit.$itemId'
import { Route as ApiShowcaseOgSlugRouteImport } from './routes/api/showcase/og/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuzzRoute = BuzzRouteImport.update({
  id: '/buzz',
  path: '/buzz',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseIndexRoute = ShowcaseIndexRouteImport.update({
  id: '/showcase/',
  path: '/showcase/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseSlugRoute = ShowcaseSlugRouteImport.update({
  id: '/showcase/$slug',
  path: '/showcase/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseAdminRoute = ShowcaseAdminRouteImport.update({
  id: '/showcase/admin',
  path: '/showcase/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseMineRoute = ShowcaseMineRouteImport.update({
  id: '/showcase/mine',
  path: '/showcase/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseSubmitRoute = ShowcaseSubmitRouteImport.update({
  id: '/showcase/submit',
  path: '/showcase/submit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseBuilderHandleRoute = ShowcaseBuilderHandleRouteImport.update({
  id: '/showcase/builder/$handle',
  path: '/showcase/builder/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseEditItemIdRoute = ShowcaseEditItemIdRouteImport.update({
  id: '/showcase/edit/$itemId',
  path: '/showcase/edit/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShowcaseOgSlugRoute = ApiShowcaseOgSlugRouteImport.update({
  id: '/api/showcase/og/$slug',
  path: '/api/showcase/og/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buzz': typeof BuzzRoute
  '/login': typeof LoginRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/showcase/admin': typeof ShowcaseAdminRoute
  '/showcase/mine': typeof ShowcaseMineRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/showcase/builder/$handle': typeof ShowcaseBuilderHandleRoute
  '/showcase/edit/$itemId': typeof ShowcaseEditItemIdRoute
  '/api/showcase/og/$slug': typeof ApiShowcaseOgSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buzz': typeof BuzzRoute
  '/login': typeof LoginRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/showcase/admin': typeof ShowcaseAdminRoute
  '/showcase/mine': typeof ShowcaseMineRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/showcase': typeof ShowcaseIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/showcase/builder/$handle': typeof ShowcaseBuilderHandleRoute
  '/showcase/edit/$itemId': typeof ShowcaseEditItemIdRoute
  '/api/showcase/og/$slug': typeof ApiShowcaseOgSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buzz': typeof BuzzRoute
  '/login': typeof LoginRoute
  '/showcase/$slug': typeof ShowcaseSlugRoute
  '/showcase/admin': typeof ShowcaseAdminRoute
  '/showcase/mine': typeof ShowcaseMineRoute
  '/showcase/submit': typeof ShowcaseSubmitRoute
  '/showcase/': typeof ShowcaseIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/showcase/builder/$handle': typeof ShowcaseBuilderHandleRoute
  '/showcase/edit/$itemId': typeof ShowcaseEditItemIdRoute
  '/api/showcase/og/$slug': typeof ApiShowcaseOgSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buzz'
    | '/login'
    | '/showcase/$slug'
    | '/showcase/admin'
    | '/showcase/mine'
    | '/showcase/submit'
    | '/showcase/'
    | '/api/auth/$'
    | '/showcase/builder/$handle'
    | '/showcase/edit/$itemId'
    | '/api/showcase/og/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buzz'
    | '/login'
    | '/showcase/$slug'
    | '/showcase/admin'
    | '/showcase/mine'
    | '/showcase/submit'
    | '/showcase'
    | '/api/auth/$'
    | '/showcase/builder/$handle'
    | '/showcase/edit/$itemId'
    | '/api/showcase/og/$slug'
  id:
    | '__root__'
    | '/'
    | '/buzz'
    | '/login'
    | '/showcase/$slug'
    | '/showcase/admin'
    | '/showcase/mine'
    | '/showcase/submit'
    | '/showcase/'
    | '/api/auth/$'
    | '/showcase/builder/$handle'
    | '/showcase/edit/$itemId'
    | '/api/showcase/og/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuzzRoute: typeof BuzzRoute
  LoginRoute: typeof LoginRoute
  ShowcaseSlugRoute: typeof ShowcaseSlugRoute
  ShowcaseAdminRoute: typeof ShowcaseAdminRoute
  ShowcaseMineRoute: typeof ShowcaseMineRoute
  ShowcaseSubmitRoute: typeof ShowcaseSubmitRoute
  ShowcaseIndexRoute: typeof ShowcaseIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ShowcaseBuilderHandleRoute: typeof ShowcaseBuilderHandleRoute
  ShowcaseEditItemIdRoute: typeof ShowcaseEditItemIdRoute
  ApiShowcaseOgSlugRoute: typeof ApiShowcaseOgSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buzz': {
      id: '/buzz'
      path: '/buzz'
      fullPath: '/buzz'
      preLoaderRoute: typeof BuzzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/': {
      id: '/showcase/'
      path: '/showcase'
      fullPath: '/showcase/'
      preLoaderRoute: typeof ShowcaseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/$slug': {
      id: '/showcase/$slug'
      path: '/showcase/$slug'
      fullPath: '/showcase/$slug'
      preLoaderRoute: typeof ShowcaseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/admin': {
      id: '/showcase/admin'
      path: '/showcase/admin'
      fullPath: '/showcase/admin'
      preLoaderRoute: typeof ShowcaseAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/mine': {
      id: '/showcase/mine'
      path: '/showcase/mine'
      fullPath: '/showcase/mine'
      preLoaderRoute: typeof ShowcaseMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/submit': {
      id: '/showcase/submit'
      path: '/showcase/submit'
      fullPath: '/showcase/submit'
      preLoaderRoute: typeof ShowcaseSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/builder/$handle': {
      id: '/showcase/builder/$handle'
      path: '/showcase/builder/$handle'
      fullPath: '/showcase/builder/$handle'
      preLoaderRoute: typeof ShowcaseBuilderHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase/edit/$itemId': {
      id: '/showcase/edit/$itemId'
      path: '/showcase/edit/$itemId'
      fullPath: '/showcase/edit/$itemId'
      preLoaderRoute: typeof ShowcaseEditItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/showcase/og/$slug': {
      id: '/api/showcase/og/$slug'
      path: '/api/showcase/og/$slug'
      fullPath: '/api/showcase/og/$slug'
      preLoaderRoute: typeof ApiShowcaseOgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuzzRoute: BuzzRoute,
  LoginRoute: LoginRoute,
  ShowcaseSlugRoute: ShowcaseSlugRoute,
  ShowcaseAdminRoute: ShowcaseAdminRoute,
  ShowcaseMineRoute: ShowcaseMineRoute,
  ShowcaseSubmitRoute: ShowcaseSubmitRoute,
  ShowcaseIndexRoute: ShowcaseIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ShowcaseBuilderHandleRoute: ShowcaseBuilderHandleRoute,
  ShowcaseEditItemIdRoute: ShowcaseEditItemIdRoute,
  ApiShowcaseOgSlugRoute: ApiShowcaseOgSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
